version: "3.8"

services:
  mikrocloud:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "/app/data/mikrocloud.db"
      LOG_LEVEL: "debug"
    volumes:
      - mikrocloud_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # For Docker access
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

volumes:
  mikrocloud_data:
